// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// knn_pred_cpp
List knn_pred_cpp(NumericMatrix train_x, NumericVector train_y, NumericMatrix test_x, int k);
RcppExport SEXP _KNNreg_knn_pred_cpp(SEXP train_xSEXP, SEXP train_ySEXP, SEXP test_xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type train_x(train_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type train_y(train_ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type test_x(test_xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(knn_pred_cpp(train_x, train_y, test_x, k));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _KNNreg_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_KNNreg_knn_pred_cpp", (DL_FUNC) &_KNNreg_knn_pred_cpp, 4},
    {"_KNNreg_rcpp_hello_world", (DL_FUNC) &_KNNreg_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_KNNreg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
