# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knn_pred_cpp <- function(train_x, train_y, test_x, k) {
    .Call(`_KNNreg_knn_pred_cpp`, train_x, train_y, test_x, k)
}

rcpp_hello_world <- function() {
    .Call(`_KNNreg_rcpp_hello_world`)
}

